from enum import Enum


class EventType(Enum):

    UNKNOWN = "UNKNOWN"

    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    PRODUCT_DELAY = "PRODUCT_DELAY"
    PRODUCT_RECALL = "PRODUCT_RECALL"

    PARTNERSHIP = "PARTNERSHIP"
    CONTRACT = "CONTRACT"

    ACQUISITION = "ACQUISITION"
    MERGER = "MERGER"

    EARNINGS = "EARNINGS"
    GUIDANCE = "GUIDANCE"

    CEO_CHANGE = "CEO_CHANGE"
    EXECUTIVE_CHANGE = "EXECUTIVE_CHANGE"

    ANALYST_UPGRADE = "ANALYST_UPGRADE"
    ANALYST_DOWNGRADE = "ANALYST_DOWNGRADE"

    INSIDER_BUY = "INSIDER_BUY"
    INSIDER_SELL = "INSIDER_SELL"

    FDA_APPROVAL = "FDA_APPROVAL"

    REGULATION = "REGULATION"

    LAWSUIT = "LAWSUIT"

    SECURITY_INCIDENT = "SECURITY_INCIDENT"

    MACRO = "MACRO"